#!/bin/bash
#
# Enjoy Git while unlocking achievements for doing actions
# 
# Copyright Benjamin C. Meyer 2010 <ben@meyerhome.net>
#

ACTIONLOGFILE="$HOME/.git-achievements-action.log"
ACHIEVEMENTSLOGFILE="$HOME/.git-achievements.log"

function output_achievement
{
echo "
********************************************************************************
Git Achievement Unlocked!

$1
$2
********************************************************************************
" |  sed  -e :a -e 's/^.\{1,79\}$/ & /;ta'
}

function unlock_achievement
{
    grep "$1" ${ACHIEVEMENTSLOGFILE} > /dev/null
    if [ $? -eq 0 ] ; then
        return
    fi
    output_achievement "$@"
    output_achievement "$@" >> ${ACHIEVEMENTSLOGFILE}
}

function log_action
{
    echo "$@" >> ${ACTIONLOGFILE}
    echo -n "Date: " >> ${ACTIONLOGFILE}
    date >> ${ACTIONLOGFILE}
}

function execute_achivements_command
{
    case $2 in
        -a )
            cat ${ACHIEVEMENTSLOGFILE}
            ;;
        * )
            echo "Git Achievements"
            count=`cat ${ACHIEVEMENTSLOGFILE}| grep Unlocked | wc -l`
            echo ""
            echo "You currently have: $count achievements"
            echo ""
            echo "Options:"
            echo "    -a show all achievements"
            ;;
    esac
}

function count_command
{
    export powerof2=`awk "START {n=0} /$1/ {n++} END { print and(n, n-1) }" $ACTIONLOGFILE`
    export power=`awk "START {n=0} /$1/ {n++} END { print log(n)/log(2) }" $ACTIONLOGFILE`
    export count=`awk "START {n=0} /$1/ {n++} END { print n }" $ACTIONLOGFILE`
    #echo "$1 $powerof2 $power $count"
}

function check_for_achivements
{
   case $1 in
        achievements )
            execute_achivements_command "$@"
            exit $?
            ;;

        add )
            count_command "$@"
            if [ "${powerof2}" = "0" ] ; then
                unlock_achievement "Stone Mason (Level $power)" "$count additions to the staging area."
            fi
            case $2 in
                *.gitignore )
                unlock_achievement "Caretaker" "Kept your repository clean by adding a .gitignore file"
                ;;
                -p )
                count_command "add -p"
                if [ "${powerof2}" = "0" ] ; then
                    unlock_achievement "Miller (Level $power)" "Add only part of a file to the stage $count times."
                fi
                ;;
            esac
            ;;
        bisect )
            count_command "$@"
            if [ "${powerof2}" = "0" ] ; then
                unlock_achievement "Hunter (Level $power)" "Used git bisect $count times"
            fi
            ;;
        cherry-pick )
            count_command "$@"
            if [ "${powerof2}" = "0" ] ; then
                unlock_achievement "Cherry Picker (Level $power)" "$count cherry-picks"
            fi
            ;;
        checkout )
            case $2 in
                -b )
                count_command "checkout -b"
                if [ "${powerof2}" = "0" ] ; then
                    unlock_achievement "Blacksmith (Level $power)" "$count new branches."
                fi
                ;;
            esac
            ;;
        commit )
            count_command "$@"
            if [ "${powerof2}" = "0" ] ; then
                unlock_achievement "Wisdom (Level $power)" "$count commits"
            fi
            case $2 in
                --amend )
                count_command "commit --amend"
                if [ "${powerof2}" = "0" ] ; then
                    unlock_achievement "Seamstress (Level $power)" "$count amended commits."
                fi
                ;;
                -s )
                count_command "commit -s"
                if [ "${powerof2}" = "0" ] ; then
                    unlock_achievement "Locksmith (Level $power)" "$count signed commits."
                fi
                ;;
            esac
            ;;
        config )
            if [[ $# -ge 4 && $2 = "--global" && $3 = "user.name" ]] ; then
                unlock_achievement "Homeowner" "Set global user name."
            fi
            if [[ $# -ge 4 && $2 = "--global" && $3 = "user.email" ]] ; then
                unlock_achievement "Homeowner (Level 2)" "Set global email address."
            fi
            ;;
        diff )
            case $2 in
                --cached )
                count_command "diff --cached"
                if [ "${powerof2}" = "0" ] ; then
                    unlock_achievement "Goldsmith (Level $power)" "$count reviewed patches before commiting."
                fi
                ;;
            esac

            ;;
        gc )
            count_command "$@"
            if [ "${powerof2}" = "0" ] ; then
                unlock_achievement "Chimney Sweeper" "$count garbage collections"
            fi
            ;;
        init )
            count_command "$@"
            if [ "${powerof2}" = "0" ] ; then
                unlock_achievement "Architect (Level $power)" "$count new Git repositories"
            fi
            ;;
        push )
            count_command "$@"
            if [ "${powerof2}" = "0" ] ; then
                unlock_achievement "Socialite (Level $power)" "$count pushes to a remote repository"
            fi
            ;;
        rebase )
            case $2 in
                -i )
                count_command "rebase -i"
                if [ "${powerof2}" = "0" ] ; then
                    unlock_achievement "Butcher (Level $power)" "$count interactive rebases."
                fi
                ;;
            esac
            ;;
        remote )
            case $2 in
                add )
                count_command "remote add"
                if [ "${powerof2}" = "0" ] ; then
                    unlock_achievement "Merchant (Level $power)" "Added $count external repositories."
                fi
                ;;
            esac
            ;;
        svn|p4 )
            count_command "$@"
            if [ "${powerof2}" = "0" ] ; then
                unlock_achievement "Traveler (Level $power)" "$count dealings with another rcs."
            fi
            ;;
    esac

    case $2 in
        --help )
            unlock_achievement "Student" "Accessed the documentation for a Git command"
            ;;
    esac

    hooks=`ls .git/hooks/ | grep -v sample | wc -l`
    if [ $hooks -ge 1 ] ; then
        unlock_achievement "Master Carpenter (Level: $hooks)" "Custom installed hooks."
    fi
}

git "$@"

log_action $@
check_for_achivements $@

